In [7]:
import matplotlib.pyplot as plt
import numpy as np
y = np.zeros(5)
x = np.linspace(0,1,5)

In [33]:
N = 2
pos = np.zeros((N*N,2))
for i in range(0, N*N):
    ix = i//(N)
    iy = i%(N)
    pos[i] = [1/(N-1) * ix, iy *1/(N-1)]

In [34]:
pos

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]])

In [17]:
from mpl_toolkits import mplot3d
import numpy as np
import matplotlib.pyplot as plt
N=5

def det(x_val,y_val,x1,y1,x2,y2):
    return (x1-x_val)*(y2-y_val) - (x2-x_val)*(y1-y_val)

def Element_Stiffness_Matrix(x1,y1,x2,y2,x3,y3):
    A = np.array([[x1,y1,1],[x2,y2,1],[x3,y3,1] ])
    b1 = np.array([1,0,0])
    b2 = np.array([0,1,0]) 
    b3 = np.array([0,0,1])
    grad = np.zeros((3,2))
    [a,b,c] = np.linalg.solve(A,b1)
    grad[0] = [a,b]
    [a,b,c] = np.linalg.solve(A,b2)
    grad[1] = [a,b]
    [a,b,c] = np.linalg.solve(A,b3)
    grad[2] = [a,b]

    res = np.zeros((3,3))
    area_triangle = abs(det(x1,y1,x2,y2,x3,y3))/2
    for i in range(0,3):
        for j in range(0,3):
            res[i][j] = np.dot(grad[i],grad[j])
    return area_triangle * res

In [35]:
triangle = np.zeros((N*N*2, 3))
for i in range(0, N*N*2):
    j = i//2
    jx = j//N
    jy = j%N
    if i%2 == 0:
        triangle[i] = [j,j+N,j+N+1]
    else:
        triangle[i] = [j,j+1,j+N+1]
    

In [36]:
triangle

array([[0., 2., 3.],
       [0., 1., 3.],
       [1., 3., 4.],
       [1., 2., 4.],
       [2., 4., 5.],
       [2., 3., 5.],
       [3., 5., 6.],
       [3., 4., 6.]])

In [15]:
pos

array([[0.  , 0.  ],
       [0.25, 0.5 ],
       [0.5 , 0.  ],
       [0.75, 0.5 ]])