In [20]:

# Python program to create
# sparse matrix using csc_matrix()
  
# Import required package
import numpy as np
from scipy.sparse import csc_matrix
  
row = np.array([0, 0, 1, 1, 2, 1])
col = np.array([0, 1, 2, 0, 2, 2])
  
# taking data
data = np.array([1, 4, 5, 8, 9, 6])
  
# creating sparse matrix
sparseMatrix = csc_matrix((data, (row, col)),
                          shape = (3, 3)).toarray()
  
# print the sparse matrix
print(sparseMatrix)

[[ 1  4  0]
 [ 8  0 11]
 [ 0  0  9]]


In [21]:
# Python program to
# demonstrate sets
 
# Same as {"a", "b", "c"}
myset = set(["a", "b", "c"])
print(myset)
 
# Adding element to the set
myset.add("d")
print(myset)

{'a', 'c', 'b'}
{'a', 'd', 'c', 'b'}


In [22]:
streaming = ['netflix', 'hulu', 'disney+', 'appletv+']

index = streaming.index('dis')
print('The index of disney+ is:', index)

ValueError: 'dis' is not in list

In [23]:
from scipy.sparse import lil_matrix
from scipy.sparse.linalg import spsolve
from numpy.linalg import solve, norm
from numpy.random import rand
import scipy

In [24]:
A = lil_matrix((1000, 1000))
A[0, :100] = rand(100)
A[1, 100:200] = A[0, :100]
A[1,2] = 3
A.setdiag(rand(1000))

In [25]:
A

<1000x1000 sparse matrix of type '<class 'numpy.float64'>'
	with 1200 stored elements in List of Lists format>

In [26]:
A = A.tocsr()
b = rand(1000)
x = spsolve(A, b)

In [27]:
x_ = solve(A.toarray(), b)

In [28]:
err = norm(x-x_)
err < 1e-10

True

In [30]:
M =100
N = 10
R = 100
C = 100

A = scipy.sparse.bsr_array(blocksize=(R,C))

TypeError: bsr_matrix.__init__() missing 1 required positional argument: 'arg1'